# This is a basic workflow to help you get started with Actions

name: update
on:
  push:
  schedule:
    - cron: '0/28 * * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://fancy-brook-66ae.vek.workers.dev https://winetricks-heroku.vek.workers.dev https://vek-winetricks-librarys.herokuapp.com https://t.vek.workers.dev https://winetricks-panindex.herokuapp.com
