# This is a basic workflow to help you get started with Actions

name: update     
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://httpbin.org/get https://fancy-brook-66ae.vek.workers.dev
